AllCops:
  Exclude:
    - settings.example.rb
    - spec/settings/settings.rb

LineLength:
  Enabled: false

FileName:
  Enabled: false

Encoding:
  Enabled: false

HashSyntax:
  Enabled: false

MethodLength:
  Max: 30

Documentation:
  Enabled: false

ColonMethodCall:
  Enabled: false

NumericLiterals:
  Enabled: false

BlockNesting:
  Max: 4
